name: Build plugin

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Check for files
        run: |
          ls -la
          cat LICENSE
      
      - name: Build plugin
        run: |
          mkdir -p dist
          cp -r *.js *.json SynapseLogo.png README.md LICENSE dist/ || echo "Some files might not exist"
          ls -la dist/
      
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
